routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('daftar/success/{token}', 'InvestorController@success')->name('daftar.success');
Route::resource('daftar', 'InvestorController');
Route::resource('investor', 'InvestorController');

Route::resource('investor-payment', 'InvestorPaymentController');

Route::get('{page?}', 'PageController');

app/Investor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Investor extends Model
{
    protected $fillable = [
    	'no',
    	'name',
    	'alamat',
    	'hp',
    	'email',
    	'no_ktp',
    	'scan_ktp',
    	'jumlah_investasi',
        'jumlah_saham',
        'min_belanja',
    	'token', 
    ];

    public function payment()
    {
    	return $this->hasOne(\App\InvestorPayment::class);
    }

    public function setNoAttribute($value)
    {
        $this->attributes['no'] = $this->lastNo();
    }

    public function setTokenAttribute($value)
    {
        $this->attributes['token'] = str_random(64);
    }

    public static function lastNo()
    {
        $no = '0001';

        $investor = self::orderBy('id', 'desc')->take(1)->first();

        if($investor)
        {
            $no = sprintf('%04d', (int)$investor->no +1);
        }

        return $no;
    }
}

app/Http/Controllers/InvestorController.php
<?php

namespace App\Http\Controllers;

use App\Investor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class InvestorController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * List
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function index(Request $request)
    {
        return redirect()->route('daftar.create');

        $data = [
            'investors' => Investor::paginate(10),
            'columns'   => ['No', 'Nama', 'Alamat', 'Hp', 'Investasi (Rp) <br/> (Planing)', 'Saham', '&nbsp;']
        ];

    	return view('investor.index', $data);
    }

    /**
     * Form Tambah
     * @return [type] [description]
     */
    public function create()
    {
        $no = $this->generateNo();

        $min_belanja = $this->rangeBelanja();

    	return view('investor.create', compact('no', 'min_belanja'));
    }

    /**
     * Post form tambah
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function store(Request $request)
    {
        $inputs = [];
        $this->validate($request, [
                'no'                => 'required',
                'name'              => 'required',
                'alamat'            => 'required',
                'hp'                => 'required',
                'jumlah_investasi'  => 'required',
                'jumlah_saham'      => 'required',
                'min_belanja'       => 'required',
            ]);

        # upload scan ktp
        if($request->hasFile('scan_ktp'))
        {
            $file = $this->storeScanPhoto($request->file('scan_ktp'));

            $inputs['scan_ktp'] = $request->scan_ktp->isValid() && $file ? $file : '';
        }

        if($request->opt_min_belanja && $request->opt_min_belanja >= 1000*1000)
        {
            $inputs['min_belanja'] = $request->opt_min_belanja;
        }

        $inputs['token'] = 1;

        $inputs = array_merge($request->except(['_method', '_token']), $inputs);

        $investor = Investor::create($inputs);

        $investor->payment()->create([]);

    	if($investor)
    	{
            $messages = [
                    'Berhasil daftar investor',
                    'Lengkapi data <strong>NO KTP</strong> dan <strong>Upload Scan KTP</strong>'
                ];
    		return redirect()
                    ->route('daftar.success', $investor->token)
                    ->with('messages', $messages);
    	}

    	return redirect()->back()->with('errors', ['Gagal, ada suatu masalah']);
    }

    /**
     * Form Edit
     * @param  Request $request [description]
     * @param  [type]  $id      [description]
     * @return [type]           [description]
     */
    public function edit(Request $request, $id)
    {
    	$investor = Investor::findOrFail($id);

    	return view('investor.edit', compact('investor'));
    }

    /**
     * PUT form edit
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
                'no'        => 'required',
                'name'      => 'required',
                'alamat'    => 'required',
                'hp'        => 'required',
                'no_ktp'    => 'required'
            ]);

        $inputs = [];
        # upload scan ktp
        if($request->hasFile('scan_ktp'))
        {
            $file = $this->storeScanPhoto($request->file('scan_ktp'));

            $inputs['scan_ktp'] = $request->scan_ktp->isValid() && $file ? $file : '';
        }

        $inputs['email'] = is_null($request->email) ? '' : $request->email;

        $inputs = array_merge($request->except(['_method', '_token']), $inputs);

        Investor::where('id', $id)->update( $inputs );

        return redirect()->route('daftar.edit', $id);
    }

    public function destroy($id)
    {
        $investor = Investor::findOrFail($id);

        $ktp = storage_path('app/img/upload/'.$investor->scan_ktp);

        DB::beginTransaction();

        if($investor->delete())
        {
            if(file_exists(($ktp)))
            {
                unlink($ktp);
            }
        }

        DB::commit();

        session('messages', ['Berhasil hapus !']);

        return json_encode(['url' => route('investor.index')]);
    }

    public function success(Request $request, $token)
    {
        $investor = Investor::where('token')->first();

        return view('investor.success', compact('investor'));
    }

    protected function storeScanPhoto($file)
    {
        $ext = $file->extension();

        if(!in_array($ext, ['png', 'jpg', 'jpeg', 'gif', 'bitmap']))
        {
            return false;
        }

        $path = $file->store('img/upload');

        $files = explode('/', $path);

        return end($files);
    }

    protected function generateNo()
    {
        return Investor::lastNo();
    }

    protected function rangeBelanja()
    {
        return range(300, 900, 100);
    }
}

resources/views/investor/create.blade.php
@extends('layouts.front')

@section('content')

	<div class="jumbotron">
		<div class="container">
			<h1>Daftar Investor</h1>
			<p>Daftar menjadi investor</p>
		</div>
	</div>
	
	<div class="container">
		<form action="{{ route('daftar.store') }}" method="post" enctype="multipart/form-data">
		
			@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
			@if (session('errors'))
			    <div class="alert alert-danger">
			        <ul>
			            @foreach (session('errors') as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif

			<div class="row">
				<div class="col-sm-6">
						{{ csrf_field() }}
					    <div class="panel panel-default">
					        <div class="panel-heading">
					            <h3 class="panel-title">Mohon isikan form berikut</h3>
					        </div>
					        <div class="panel-body">
					        	<div class="row">
					        		<div class="col-sm-6">
							            <div class="form-group {{ $errors->has('no') ? 'has-error':'' }}">
							            	<label class="control-label">No:</label>
							            	<input type="text" 
							            			class="form-control" required 
							            			name="no" 
							            			readonly="true" 
							            			value="{{ $no }}" />
							            </div>
							            <div class="form-group {{ $errors->has('name') ? 'has-error':'' }}">
							            	<label class="control-label">Nama:</label>
							            	<input type="text" 
							            			name="name" 
							            			class="form-control" 
							            			value="{{ old('name') }}"
							            			required />
							            </div>
							            <div class="form-group {{ $errors->has('hp') ? 'has-error':'' }}">
							            	<label class="control-label">HP:</label>
							            	<input type="text" 
							            			name="hp" 
							            			value="{{ old('hp') }}"
							            			class="form-control" required />
							            </div>
							            <div class="form-group {{ $errors->has('alamat') ? 'has-error':'' }}">
							            	<label class="control-label">Alamat:</label>
							            	<textarea class="form-control" required name="alamat">{{ old('alamat') }}</textarea>
							            </div>
							            <div class="form-group {{ $errors->has('email') ? 'has-error':'' }}">
							            	<label class="control-label">Email:</label>
							            	<input type="email" name="email" value="{{ old('email') }}" class="form-control" />
							            </div>
					        		</div>
					        			
					        		<div class="col-sm-6">
							            <div class="form-group {{ $errors->has('jumlah_investasi') ? 'has-error':'' }}">
							            	<label class="control-label">Investasi:</label>
							            	<div class="input-group">
							            		<div class="input-group-addon">Rp.</div>
							            		<input type="number" 
							            				step="100000"  
							            				min="100000"  
							            				name="jumlah_investasi" 
							            				v-model="investor.jumlah_investasi" 
							            				class="form-control" 
							            				value=""
							            				required />
							            	</div>
							            </div>
							            <div class="form-group {{ $errors->has('jumlah_saham') ? 'has-error':'' }}">
							            	<label class="control-label">Saham:</label>
							            	<div class="input-group">
							            		<input type="jumlah_saham" 
							            				name="jumlah_saham" 
							            				readonly 
							            				v-model="investor.jumlah_saham" 
							            				class="form-control" 
							            				value="" />
							            		<div class="input-group-addon">Lembar</div>
							            	</div>
							            </div>

							            <hr/>

				                        <div class="form-group {{ $errors->has('no_ktp') ? 'has-error':'' }}">
				                            <label class="control-label">NO KTP:</label>
				                            <input type="text" 
				                                    name="no_ktp" 
				                                    class="form-control"
				                                    required 
				                                    value="{{ old('no_ktp') }}" />
				                        </div>

				                        <div class="form-group {{ $errors->has('scan_ktp') ? 'has-error':'' }}">
				                            <label class="control-label">Upload Scan KTP:</label>
				                            <input type="file" name="scan_ktp" id="scan_ktp" required="required" />
				                        </div>

				                        <div class="form-group">
				                        	<div class="checkbox">
				                        		<label>
				                        			<input type="checkbox" name="skip_upload" v-model="input.skip_upload">
				                        			Lewati upload scan KTP
				                        		</label>
				                        	</div>
				                        </div>
					        		</div>

					        	</div>
					        </div>
					    </div>
					
				</div>
				<div class="col-sm-6">
					<h3>Penting diperhatikan !</h3>
					<p>Saya mengerti dan paham bahwa dengan menjadi bagian dari Madeena Mart, saya berkomitmen untuk belanja di toko Madeena Mart dengan minimal belanja senilai:</p>
					<div class="row">
						<div class="col-sm-6">
							<div class="form-group">
								<select name="min_belanja" 
										v-model="input.min_belanja" 
										@change="onSelectMinBelanja" 
										required 
										class="form-control">
									@foreach($min_belanja as $key => $min)
									<option value="{{ $min*1000 }}">{{ $min }} Ribu</option>
									@endforeach
									<option value="0">1Juta ke atas</option>
								</select>
								<p class="text-muted" style="font-size: 12px; font-style: italic;">Pilih minimal nilai belanja</p>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="form-group" v-if="input.opt_min_belanja != 0">
								<input type="number" 
										:step="harga" 
										:min="10*harga" 
										name="opt_min_belanja" 
										v-model="input.opt_min_belanja" 
										required  
										class="form-control">
								<p class="text-muted" style="font-size: 12px; font-style: italic;">Masukkan nilai belanja 1juta ke atas</p>
							</div>
						</div>
					</div>


					<div class="form-group">
						<button type="submit" class="btn btn-primary">Daftar</button>
					</div>
				</div>
			</div>
		</form>
	</div>
	
@endsection

@push('scripts')
<script>
	new Vue({
		el: '#app',
		data: {
			investor: {
				jumlah_investasi: '{{ old('jumlah_investasi', 1000000) }}',
				jumlah_saham: '{{ old('jumlah_saham', 10) }}',
			},
			// harga saham perlembar
			harga: 100000,
			input: {
				scan_ktp: false,
				skip_upload: false,
				min_belanja: '{{ old('min_belanja', 300*1000) }}',
				opt_min_belanja: 0,
			}
		},
		watch: {
			investor: {
				handler(value){
					var invs = value.jumlah_investasi;
					if(!invs) return;

					if(invs%this.harga != 0)
					{
						toastr.warning('Jumlah investasi kelipatan '.this.harga);
						this.investor.jumlah_investasi = value.jumlah_saham*this.harga;
						return false;
					}

					this.investor.jumlah_saham = parseInt(invs)/this.harga;
				},
				deep: true
			},
			input: {
				handler(value){
					var scanKtp = document.querySelector('#scan_ktp')
					var opt_min = value.opt_min_belanja

					if(!value.skip_upload)
					{
						scanKtp.setAttribute('required', 'required')
					}
					else{
						scanKtp.removeAttribute('required')
					}

					if(opt_min != 0 && opt_min < 1000*1000)
					{
						this.input.opt_min_belanja = 1000000;
						toastr.warning('Nilai belanja minimal 1Juta')
					}
				},
				deep: true
			}
		},
		methods: {
			onSelectMinBelanja(e){
				if(e.target.value == 0)
				{
					this.input.opt_min_belanja = 1000*1000;
				}
				else{
					this.input.opt_min_belanja = 0;
				}
			}
		}
	})
</script>
@endpush

resources/views/investor/edit.blade.php
@extends('layouts.front')

@section('content')

<div class="container">
    <div class="jumbotron">
        <div class="container">
            <h1>Edit Data</h1>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if (session('messages'))
        <div class="alert alert-success">
            <ul>
                @foreach (session('messages') as $msg)
                    <li>{!! $msg !!}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('investor.update', $investor->id) }}" method="post" enctype="multipart/form-data">
        {{ method_field('PUT') }}
        {{ csrf_field() }}

        <div class="row">
            <div class="col-sm-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Edit Investor</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group {{ $errors->has('no') ? 'has-error':'' }}">
                                    <label class="control-label">No:</label>
                                    <input type="text" 
                                            class="form-control" 
                                            name="no" 
                                            readonly="true" 
                                            value="{{ old('no', $investor->no) }}" />
                                </div>
                                <div class="form-group {{ $errors->has('name') ? 'has-error':'' }}">
                                    <label class="control-label">Nama:</label>
                                    <input type="text" 
                                            name="name" 
                                            class="form-control" 
                                            required
                                            value="{{ old('name', $investor->name) }}" />
                                </div>
                                <div class="form-group {{ $errors->has('hp') ? 'has-error':'' }}">
                                    <label class="control-label">HP:</label>
                                    <input type="text" 
                                            name="hp" 
                                            class="form-control"
                                            required
                                            value="{{ old('hp', $investor->hp) }}" />
                                </div>
                                <div class="form-group {{ $errors->has('alamat') ? 'has-error':'' }}">
                                    <label class="control-label">Alamat:</label>
                                    <textarea class="form-control" required name="alamat">{{ old('alamat', $investor->alamat) }}</textarea>
                                </div>
                                <div class="form-group {{ $errors->has('email') ? 'has-error':'' }}">
                                    <label class="control-label">Email:</label>
                                    <input type="email" 
                                            name="email" 
                                            class="form-control"
                                            value="{{ old('email', $investor->email) }}" />
                                </div>
                            </div>
                                
                            <div class="col-sm-6">
                                <div class="form-group {{ $errors->has('jumlah_investasi') ? 'has-error':'' }}">
                                    <label class="control-label">Jumlah Investasi (Rp):</label>
                                    <div class="input-group">
                                        
                                        <div class="input-group-addon">Rp.</div>
                                        <input type="number" 
                                                name="jumlah_investasi"
                                                v-model="investor.jumlah_investasi"
                                                step="100000" 
                                                class="form-control">
                                    </div>
                                </div>
                                <div class="form-group {{ $errors->has('jumlah_saham') ? 'has-error':'' }}">
                                    <label class="control-label">Jumlah Saham:</label>
                                    <div class="input-group">
                                        <input type="number" 
                                                name="jumlah_saham" 
                                                readonly 
                                                v-model="investor.jumlah_saham"
                                                class="form-control">
                                        <div class="input-group-addon">Lembar</div>
                                        
                                    </div>
                                </div>

                                <hr/>

                                <div class="form-group {{ $errors->has('no_ktp') ? 'has-error':'' }}">
                                    <label class="control-label">NO KTP:</label>
                                    <input type="text" 
                                            name="no_ktp" 
                                            class="form-control"
                                            required 
                                            value="{{ old('no_ktp', $investor->no_ktp) }}" />
                                </div>

                                <div class="form-group {{ $errors->has('scan_ktp') ? 'has-error':'' }}">
                                    <label class="control-label">{{ $investor->scan_ktp ? 'Ganti' : 'Upload' }} Scan KTP:</label>
                                    <input type="file" name="scan_ktp" />
                                </div>
                                
                                @if($investor->scan_ktp)
                                <div class="form-group">
                                    <img src="{{ url('img/upload', $investor->scan_ktp) }}" class="img-responsive">
                                </div>
                                @endif
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer text-right">
                        <button class="btn btn-success" type="submit">
                            <i class="fa fa-save"></i>
                            Update
                        </button>
                        <a href="{{ route('investor.index') }}" class="btn btn-link">Cancel</a>
                    </div>
                </div>
                
            </div>
        </div>
    </form>

    <form id="delete" action="{{ route('investor.destroy', $investor->id) }}" method="DELETE">
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
        <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <button class="btn btn-danger" type="submit">
                            <span class="glyphicon glyphicon-trash"></span> 
                            Hapus
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

@push('scripts')
    <script>
    new Vue({
        el: '#app',
        data: {
            investor: {
                jumlah_investasi: '{{ old('jumlah_investasi', $investor->jumlah_investasi) }}',
                jumlah_saham: '{{ old('jumlah_saham', $investor->jumlah_saham) }}',
            },
            // harga saham perlembar
            harga: 100000,
        },
        watch: {
            investor: {
                handler(value){
                    var invs = value.jumlah_investasi;
                    if(!invs) return;

                    if(invs%this.harga != 0)
                    {
                        toastr.warning('Jumlah investasi kelipatan 100.000');
                        this.investor.jumlah_investasi = value.jumlah_saham*this.harga;
                        return false;
                    }

                    this.investor.jumlah_saham = parseInt(invs)/this.harga;
                },
                deep: true
            }
        }
    })
    var $form = $('#delete');

        $form.submit(function(e){

            if(!confirm('Yakin Hapus ?')) return false;

            var data = {
                _method: $form.attr('method')
            }

            axios.post($form.attr('action'), data)
                    .then(function(res){
                        toastr.success('Hapus Berhasil!')
                        setTimeout(function(){
                            window.location.href = res.data.url
                        }, 2000)

                    })

            e.preventDefault()
        })
    </script>
@endpush

resources/views/investor/index.blade.php
@extends('layouts.front')

@push('styles')
	<style>
		.menu {
			margin-top: 3.4em
		}
	</style>
@endpush

@section('content')
	@if (session('messages'))
        <div class="alert alert-success">
            <ul>
                @foreach (session('messages') as $msg)
                    <li>{!! $msg !!}</li>
                @endforeach
            </ul>
        </div>
    @endif
	<p class="text-right">
		<a href="{{ route('investor.create') }}" class="btn btn-success">
		<span class="glyphicon glyphicon-plus"></span>Daftar Investor</a>
	</p>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Investor</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
            	<thead>
            		<tr>
            			@foreach($columns as $column)
            				<th>{!! $column !!}</th>
            			@endforeach
            		</tr>
            	</thead>
            	<tbody>
            		@if($investors->count())
            			@foreach($investors as $investor)
            			<tr>
            				<td>{{ $investor->no }}</td>
            				<td>{{ $investor->name }}</td>
            				<td>{{ $investor->alamat }}</td>
            				<td>{{ $investor->hp }}</td>
            				<td>Rp. {{ $investor->jumlah_investasi ? number_format($investor->jumlah_investasi) : 0 }}</td>
            				<td>{{ $investor->jumlah_saham }}</td>
            				<td>
            					<a href="{{ route('investor.edit', $investor->id)}}" class="btn btn-primary btn-sm">
            						Detail
            					</a>
            				</td>
            			</tr>
            			@endforeach
            		@endif
            	</tbody>
            </table>
        </div>
        <div class="panel-footer">
			@if($investors->count())
				{{ $investors->links() }}
			@else
				<p class="text-muted">Data Kosong</p>
			@endif
        </div>
    </div>
@endsection

resources/views/investor/success.blade.php
@extends('layouts.front')

@section('content')
	<h2>&nbsp;</h2>
	<div class="container text-center">
		<div class="alert alert-success">
			Pendaftaran Berhasil.
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<h1>Selamat! sebentar lagi anda terdaftar menjadi investor</h1>
				<p>Untuk proses pengesahan, silahkan transfer dana Rp. <h3 class="text-danger"> {{ $investor->jumlah_investasi ? number_format($investor->jumlah_investasi) : '--' }}</h3> ke:</p>

				<p>
					Bank Syariah Mandiri<br/>
					7-1111-499-89<br/>
					PT. SOUQ MADEENA INDONESIA
				</p>
			</div>
		</div>

		<p style="margin-bottom: 26px">
			<a href="{{ url('/') }}" class="btn btn-default">
				<span class="glyphicon glyphicon-home"></span> 
				Ke Halaman utama
			</a>
		</p>

	</div>
@endsection